spring.application.name=H2Database
server.port= 8092

spring.datasource.url=jdbc:mysql://database-arun.cvcao0sqa86i.eu-north-1.rds.amazonaws.com:3306/database-arun
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=FuAssX0qMDkVzqoDD9Ip
spring.jpa.hibernate.ddl-auto=update